name: adb_dart
description: A lightweight Dart client for interacting with Android devices through ADB (Android Debug Bridge). List devices, install APKs, read logcat, and more.
version: 1.2.2
repository: https://github.com/ThomasBernard03/adb_dart
homepage: https://github.com/ThomasBernard03/adb_dart

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
